# Generated by Django 4.2.3 on 2023-07-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('codechef_user', models.CharField(max_length=50)),
                ('codeforces_user', models.CharField(max_length=50)),
                ('leetcode_user', models.CharField(max_length=50)),
            ],
        ),
    ]
